externalManifests:
- type: json
  file: 'synth.metadata'
  jsonpath: '$.generatedFiles[*]'
- type: json
  file: '.github/readme/synth.metadata/synth.metadata'
  jsonpath: '$.generatedFiles[*]'
ignoreAuthors:
- 'renovate-bot'
- 'yoshi-automation'
- 'release-please[bot]'
- 'gcf-owl-bot[bot]'
