bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 1.39.2-sp
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.40.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.41.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.42.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.43.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.44.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.46.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.47.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: protobuf-4.x-rc
    manifest: true
