bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - branch: 1.39.2-sp
    releaseType: java-lts
  - branch: 1.40.x
    releaseType: java-backport
  - branch: 1.41.x
    releaseType: java-backport
  - branch: 1.42.x
    releaseType: java-backport
  - branch: 1.43.x
    releaseType: java-backport
  - branch: 1.44.x
    releaseType: java-backport
  - branch: 1.46.x
    releaseType: java-backport
  - branch: 1.47.x
    releaseType: java-backport
  - branch: protobuf-4.x-rc
    manifest: true
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 2.1.x
