bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
    - releaseType: java-lts
      branch: 1.39.2-sp
    - releaseType: java-backport
      branch: 1.40.x
    - releaseType: java-backport
      branch: 1.41.x
    - releaseType: java-backport
      branch: 1.42.x
    - releaseType: java-backport
      branch: 1.43.x
    - releaseType: java-backport
      branch: 1.44.x
    - releaseType: java-backport
      branch: 1.46.x
    - releaseType: java-backport
      branch: 1.47.x
    - branch: protobuf-4.x-rc
      manifest: true
